### PR TITLE
adding figure drafts

### PR DESCRIPTION
**Pull request by hannaheps**

### CODE REVIEW

**Comment by zaneveld** [comment]
Thanks Hannah! Just one issue - It looks like this branch also has some additional conflicts based on the supplemental tables .xlsx file? Can you resolve them and recommit, or go back to main, pull updates, then start a new branch and add your updated figures there (so we won't have to manually resolve conflicts on the command line)?

**Comment by hannaheps** [comment]
Sorry about that Jesse! I've just pulled & re-committed on another branch. Let me know if there are any other issues.

**Comment by zaneveld** [comment]
Hmm still looks like there are conflicts :(. 

Here's the message I get:

This branch has conflicts that must be resolved
 to resolve conflicts before continuing.
Conflicting files
products/manuscript/figures/figure_3/Figure3_TreeHeatmap_version4.pdf
products/manuscript/figures/figure_4/figure4_conceptual.pdf
products/manuscript/figures/figure_4/figure4_conceptual_v2.pdf
products/manuscript/supplementary_materials/SuppFigure_CausalityModels.pdf
products/manuscript/supplementary_materials/supplemental_tables.xlsx

**Comment by hannaheps** [comment]
After pulling the latest repo version, it looks like all the right files have actually made it in, despite these issues. Can we just close this pull request instead of incorporating it?

**Comment by zaneveld** [comment]
This was added by another pull request, so we'll just close the PR - thanks!

**Pull request closed without merging**
